name: linux_appimage

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'README_zh_HK.md'
      - 'README_ja_JP.md'
      - 'DEVELOPNOTE.md'
      - 'DEVELOPNOTE_zh_CN.md'
      - 'CHANGELOG.md'
      - 'CODE_OF_CONDUCT.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE/**'
      - 'TODO.md'
      - '.readthedocs.yaml'
    tags:
      - V**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'README_zh_HK.md'
      - 'README_ja_JP.md'
      - 'DEVELOPNOTE.md'
      - 'DEVELOPNOTE_zh_CN.md'
      - 'CHANGELOG.md'
      - 'CODE_OF_CONDUCT.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE/**'
      - 'TODO.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  appimage:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'
          modules: 'qtwebsockets qtserialport qtmultimedia'
          aqtversion: '==3.1.20'

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y make gcc patchelf chrpath qt5-default libxcb-cursor0 build-essential libgtk-3-dev
      
      - name: Install setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build fcitx_qt6
        run: |
          cd depend
          sudo apt install fcitx-libs-dev qtbase5-private-dev libxkbcommon-dev extra-cmake-modules tree
          export PATH=$Qt6_DIR/bin:$PATH
          export PATH=$Qt6_DIR/../../Qt/Tools/CMake/bin:$PATH
          export Qt6GuiTools_DIR=$Qt6_DIR
          ./build_fcitx_qt6_linux.sh
          cp ./fcitx-qt5-1.2.7/build/qt6/platforminputcontext/libfcitxplatforminputcontextplugin-qt6.so ./

      - name: build libssh2
        run: |
          cd depend
          export PATH=$Qt6_DIR/bin:$PATH
          ./build_libssh2.sh
          sudo cp -R ./output /usr/local/

      - name: Build all
        run: |
          git fetch --tags --force
          sed -i 's/--long --dirty/--long/g' ./tools/generate_info.sh
          sed -i 's/QT_DIR=\/opt\/Qt6.2.0\/6.2.0\/gcc_64/QT_DIR=$(cd "$(dirname "$0")";pwd)\/..\/Qt\/6.8.1\/gcc_64/g' build_AppImage.sh
          sed -i 's/LIBSSH2_DIR=\/libssh2/LIBSSH2_DIR=\/usr\/local\/output/g' ./lib/qtssh/qtssh.pri
          mkdir prebuilt_plugins
          python3 ./.github/scripts/get_plugin.py ./.github/scripts/plugin_list.json ./prebuilt_plugins
          ./build_AppImage.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v4
        with:
          name: quardCRT_AppImage
          path: |
            ./AppImageOut/*.AppImage
            