name: macos

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'README_zh_HK.md'
      - 'README_ja_JP.md'
      - 'DEVELOPNOTE.md'
      - 'DEVELOPNOTE_zh_CN.md'
      - 'CHANGELOG.md'
      - 'CODE_OF_CONDUCT.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE/**'
      - 'TODO.md'
      - '.readthedocs.yaml'
    tags:
      - V**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'README_zh_HK.md'
      - 'README_ja_JP.md'
      - 'DEVELOPNOTE.md'
      - 'DEVELOPNOTE_zh_CN.md'
      - 'CHANGELOG.md'
      - 'CODE_OF_CONDUCT.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE/**'
      - 'TODO.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          modules: 'qtwebsockets qtserialport qtmultimedia'
          aqtversion: '==3.1.20'

      - name: Install prerequisites
        run: |
          ruby - e  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null  2 > /dev/null
          brew install --build-from-source cmake
          brew install create-dmg
          brew install coreutils

      - name: Install setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build libssh2
        run: |
          cd depend
          export PATH=$Qt6_DIR/bin:$PATH
          ./build_libssh2.sh
          sudo cp -R ./output /usr/local/

      - name: Build all
        run: |
          git fetch --tags --force
          sed -i'.original' -e 's/--long --dirty/--long/g' ./tools/generate_info.sh
          sed -i'.original' -e 's/QT_DIR=\/opt\/Qt6.2.0\/6.2.0\/gcc_64/QT_DIR=$(cd "$(dirname "$0")";pwd)\/..\/Qt\/6.7.3\/macos/g' build_dmg.sh
          sed -i'.original' -e 's/LIBSSH2_DIR=\/libssh2/LIBSSH2_DIR=\/usr\/local\/output/g' ./lib/qtssh/qtssh.pri
          mkdir prebuilt_plugins
          python3 ./.github/scripts/get_plugin.py ./.github/scripts/plugin_list.json ./prebuilt_plugins
          ./build_dmg.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v4
        with:
          name: quardCRT_macos
          path: |
            ./dmgOut/*.dmg

      - name: Run tests
        run: |
          sudo hdiutil attach ./build_release/out/quardCRT.dmg
          /Volumes/quardCRT/quardCRT.app/Contents/MacOS/quardCRT --version
